services:
  api-gateway:
    build: .
    container_name: api-gateway
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - api-gateway-redis
    volumes:
      - .:/app

  api-gateway-redis:
    image: redis:7
    container_name: api-gateway-redis
    ports:
      - "6380:6379"
